# image will be published to ghcr.io/<user>/<name>
name: desktop
description: Image for desktop gaming

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    install:
      - zsh
      - gcc-c++
      - openssl-devel

  - type: default-flatpaks
    notify: true
    system:
      install:
        - net.pcsx2.PCSX2

  - type: signing

