# image will be published to ghcr.io/<user>/<name>
name: desktop
description: Image for desktop gaming

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - zsh

  #- from-file: slicer.yml # uncomment if I want to use a different slicer and it has deps, time will tell
  - from-file: docker.yml
  - from-file: vscode.yml
  - from-file: rtl.yml

  - type: default-flatpaks
    notify: true
    system:
      install:
        - net.pcsx2.PCSX2
        - com.usebottles.bottles

  - type: signing
