# image will be published to ghcr.io/<user>/<name>
name: desktop
description: Image for desktop gaming

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  - type: rpm-ostree
    repos:
      - https://download.docker.com/linux/fedora/docker-ce.repo
    install:
      - zsh
      - gcc-c++
      - openssl-devel
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - java-17-openjdk
      - snapd
      - plasma-workspace-x11

  - from-file: vscode.yml

  - type: default-flatpaks
    notify: true
    system:
      install:
        - net.pcsx2.PCSX2

  - type: signing

  - type: systemd
    system:
      enabled:
        - docker.service
